### ISSUE TITLE
Support horizontal mode

### ISSUE THREAD

**Issue by minhtranite** [a5hik/ng-sortable#7]
I use sortable directive to sort images like this:
![screenshot-127 0 0 1 9000 2014-07-01 11-31-03](https://cloud.githubusercontent.com/assets/5418628/3438981/5f7ac60e-00d9-11e4-85b7-78c349419ced.png)
with custom css :

``` css
.media-images-sortable {
  margin-left : -10px;
  .sortable-item,
  .sortable-placeholder {
    display     : inline-block;
    width       : 124px;
    height      : 110px;
    margin-left : 10px;
  }
}
```

but I can't drag & drop other item up to first item
![screenshot-127 0 0 1 9000 2014-07-01 11-32-51](https://cloud.githubusercontent.com/assets/5418628/3439038/a4fa1918-00da-11e4-8578-63d328ff7582.png)
Please add support horizontal mode. Thank!
