### ISSUE TITLE
Sorting row tables

### ISSUE THREAD

**Issue by piernik** [a5hik/ng-sortable#84]
Your plugin works well when sorting row tables (tr elements) except one thing:

``` css
.as-sortable-item, .as-sortable-placeholder {
    display: block;
}
```

this code convert rows `display:table-row` to blocks and destroys table.
I think You can delete this fragment.
