### ISSUE TITLE
Not working when as-sortable-item-handle inside directive with isolated scope

### ISSUE THREAD

**Issue by osadan** [a5hik/ng-sortable#93]
I ma using the ng-sortable as follows
```javascript
<section as-sortable ng-model='somedata'>
    <div ng-repeat>
       <div class='a'><div>
       <div class='b' as-sortable-item>
           <some-directive-with-isolated-scope as-sortable-item-handler>
      </div>
    </div>
</section>'
```
and I receive the following error on line 654 Uncaught TypeError: Cannot read property 'options' of undefined

//the row
```javascript 
 // (optional) Scrollable container as reference for top & left offset calculations, defaults to Document
            scrollableContainer = angular.element($document[0].querySelector(scope.sortableScope.options.scrollableContainer)).length > 0 ?
              $document[0].querySelector(scope.sortableScope.options.scrollableContainer) : $document[0].documentElement;
```
 the problem is that the sortableScope is inside the scope. itemScope

**Comment by piernik** [comment]
I've got the same problem. Can You fix it?

**Comment by a5hik** [comment]
Yes, the master copy has a fix for this issue, will update bower.

**Comment by piernik** [comment]
Please add also version number in js file

**Comment by rosslavery** [comment]
I have the same issue, and using the latest release *or* the master branch makes no difference.

If `as-sortable` and `as-sortable-item` are outside the directive, and `as-sortable-item-handle` is inside the directive, it spits out:
```
654 Uncaught TypeError: Cannot read property 'options' of undefined
```

**Comment by pascalbayer** [comment]
Please update bower with the latest version to enable correct functionality with elements that have an isolated scope.

**Comment by a5hik** [comment]
Will update the Bower version soon.

**Comment by Yeah69** [comment]
Got the current version (1.2.0) from rails-assets. Got the same problem.

Tryed to put the as-sortable-item into the isolated directive, but this lead to another problem:
scope.sortableScope.$apply(function () {
                scope.callbacks.dragEnd(dragItemInfo.eventArgs());
              });
Here callbacks is undefined.

**Comment by davidhartman** [comment]
I'm running into the same issue. Anyone have a fix for this?

**Comment by nizarmattar** [comment]
i'm stuck with this issue too.

**Comment by davidhartman** [comment]
I actually ended up going with a different sortable control that didn't have his issue.

**Comment by hannupekka** [comment]
I'm also having issue similar to this:
```html
<div data-as-sortable="callbacks" data-ng-model="items">
  <custom-directive ng-repeat="item in items" />
</div>
```
And then I'm using `data-as-sortable-item`and `data-as-sortable-item-handle` inside custom directive template.

The error I'm getting when dragging:
```
TypeError: Cannot read property 'dragStart' of undefined
```

**Comment by a5hik** [comment]
Ok will look in to it. also PRs welcome.

**Comment by adammartin1981** [comment]
@davidhartman What sortable did you end up going with in the end?

**Comment by davidhartman** [comment]
https://github.com/angular-ui/ui-sortable

**Comment by dragosprotung** [comment]
@a5hik Did you had some time to look into this ? I hit the same problem and unfortunately I do not even begin to know where to start to fix this issue

**Comment by a5hik** [comment]
@dragosprotung Let me update you, If I get a time to look in to this over the weekend.

**Comment by bojanbass** [comment]
Same issue here and I think ng-sortable should support isolated scopes. Any plans to fix this one?

**Comment by robertbl22twc** [comment]
I also ran into this issue trying to put as-sortable-item-handle in a directive with an isolated scope.

**Comment by a5hik** [comment]
This should be fixed with the latest commit, please let me know If it exists still.

**Comment by a5hik** [comment]
the master having the fix. I had tested by creating a directive with isolated scope and goes like this...
```
<as-sortable>
  <as-sortable-item>
      <isolated-directive>
         <as-sortable-item-handle>
```
and it works fine. as the issue reported in #93 is this. Please create a plunkr for your case.

- Ashik

**Comment by jedatu** [comment]
Would you be willing to share your test as a plnkr?  I believe I have a structure that matches your recommendation, but I keep getting. `item.index is not a function`   For some reason, the index function is located at `item.$parent.$parent.index`

**Comment by Darksoulsong** [comment]
@jedatu I second that, I got the same issue using:

    <as-sortable>
      <as-sortable-item>
          <isolated-directive>
             <as-sortable-item-handle>

**Comment by a5hik** [comment]
OK. Will do so.

**Comment by nizarmattar** [comment]
I solved this issue long time ago, now it works just perfect that way i want.
i don't remember what exactly was the main issue there, but here is how i used it in my app, hope this helps someone:

HTML:
```html
<div id="sortableContainer" data-as-sortable="dragControlListeners" data-ng-model="followers">
   <div ng-repeat="follower in followers" data-as-sortable-item class="as-sortable-item">
      <div title="Drag to reorder"  class="as-sortable-item-handle" data-as-sortable-item-handle>
         <i class="icon-resize-vertical"></i>
      </div>
      <div>
         <ir-follower ng-model="follower" extra-parameters="extraParameters"></ir-follower>
      </div>
   </div>
</div>
```

CSS:
```css
/* ************************************** */
/* Mandatory CSS required for ng-sortable */
/* ************************************** */

.as-sortable-item,
.as-sortable-placeholder {
    display: block;
}
.as-sortable-item {
    -ms-touch-action: none;
    touch-action: none;
}
.as-sortable-item-handle {} .as-sortable-placeholder {
    background-color: transparent;
}
.as-sortable-drag {
    position: absolute;
    pointer-events: none;
    z-index: 9999;
    cursor: move;
}
.as-sortable-hidden {
    display: none !important;
}
.as-sortable-un-selectable {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
/* ******************************************* */
/* Optional CSS, default style for ng-sortable */
/* ******************************************* */

.as-sortable-item,
.as-sortable-placeholder {
    min-height: 20px;
    margin: 1px 2px 5px 1px;
}
.as-sortable-item {
    /* border: solid 0px darkgrey; */
    
    background-color: #ffffff;
}
.as-sortable-item-handle {} .as-sortable-placeholder {
    /* border: 1px dashed darkgrey;*/
    
    box-sizing: border-box;
    /*  background-color: #dbdbdb;*/
}
.as-sortable-drag {
    opacity: .8;
}
.as-sortable-hidden {}
```

JAVASCRIPT:
```javascript
// settings for the sortable follower list
$scope.dragControlListeners = {
    // drag boundary
    containment: '#sortableContainer',
    accept: function(sourceItemHandleScope, destSortableScope) {
        return true;
    }, //override to determine drag is allowed or not. default is true.
    itemMoved: function(event) {},
    orderChanged: function(event) {}
};
```
